// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnjrmshddiusyqmkxmra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuanJtc2hkZGl1c3lxbWt4bXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTE0NzQsImV4cCI6MjA2NzYyNzQ3NH0.LsESssW7r3ySE48AnwZrc9WUf8_9dCSGx1G3O8q9kjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});